# Server Configuration
server:
  port: 9908
  servlet:
    context-path: /

# Spring Application
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.chevere.ddns.net/realms/kysoft-realm
          jwk-set-uri: https://auth.chevere.ddns.net/realms/kysoft-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: https://auth.chevere.ddns.net/realms/kysoft-realm/protocol/openid-connect/token
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scheduled
    username: postgres
    password: toor

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: default
    generate-ddl: true
# JWT Auth Converter Configuration
jwt:
  auth:
    converter:
      resource-id: registro-civil
      principle-attribute: preferred_username

# HTTP and CORS Configuration
http:
  cors-enabled: true
  cors:
    allowed-origins: http://localhost:8080
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: '*'
    allow-credentials: true
    max-age: 3600

# Eureka Client Configuration
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Springdoc Swagger UI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: openapi,swagger-ui
