# Server Configuration
server:
  port: 8080
  servlet:
    context-path: "/"

# Spring Application
spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: REACTIVE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.chevere.ddns.net/realms/kysoft-realm
          jwk-set-uri: https://auth.chevere.ddns.net/realms/kysoft-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: https://auth.chevere.ddns.net/realms/kysoft-realm/protocol/openid-connect/token
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  kafka:
      bootstrap-servers: localhost:29092  # Cambia esto según tu configuración de Kafka
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: group_id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Scheduler Configuration
scheduler:
  config:
    enabled: false
    initialDelay: 10
    refreshRate: 8

# JWT Configuration
jwt:
  auth:
    converter:
      resource-id: registro-civil
      principle-attribute: preferred_username

# Keycloak Configuration
keycloak:
  provider:
    server-url: https://auth.chevere.ddns.net
    realm-name: kysoft-realm
    realm-master: master
    admin-clic: admin-cli
    user-console: admin
    password-console: ZWJjMTViM2U4YjQ0MTQwZTI5ZjI1YWFk
    client-id: registro-civil
    client-secret: 1H9aICIPNYxYplgkbfR7VWdCuuuhPMeb
    grant_type: password
    default-role: ADMIN
google:
  client-id: 945296493767-ic6omj9ke4o76n11k71eq0trap4lu6r0.apps.googleusercontent.com
# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# SpringDoc Configuration
springdoc:
  swagger-ui:
    enabled: true

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: openapi,swagger-ui,gateway,refresh

# HTTP and CORS Configuration
http:
  cors-enabled: true
  cors:
    allowed-origins: http://localhost:9000
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: '*'
    allow-credentials: true
    max-age: 1800

# Logging Level
logging:
  level:
    org:
      springframework:
        cloud: DEBUG
    keycloak: DEBUG
